### ISSUE TITLE
Error during transpilation (due to broken imported module)

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#148]
The following exception was thrown in the transpiler:

"Severe problem detected in compiler=es message=name may not be null or empty."

Stacktrace:

```
java.lang.IllegalArgumentException: name may not be null or empty
    at eu.numberfour.n4js.transpiler.operations.SymbolTableManagement.getSymbolTableEntryInternal(SymbolTableManagement.java:197)
    at eu.numberfour.n4js.transpiler.TranspilerComponent.getSymbolTableEntryInternal(TranspilerComponent.java:248)
    at eu.numberfour.n4js.transpiler.es.transform.ModuleWrappingTransformation.lambda$31(ModuleWrappingTransformation.java:502)
    at eu.numberfour.n4js.transpiler.es.transform.ModuleWrappingTransformation$$Lambda$450/608845466.apply(Unknown Source)
    at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
```

I assume that the following code lead to the problem:

```
import { BrokenClass } from "some/broken/Module"
export public class SomeTest {

    @Test public test() {
        let p= new BrokenClass();
    }
```

That is, the "BrokenClass" cannot be compiled. However this should not lead to an unknown compilation error. Instead, an error like "Cannot be compiled since imported class "BrokenClass" contains errors" or something similar.

**Comment by torstenkraemer** [comment]
Cannot reproduce the Error.
