### ISSUE TITLE
Problem with API stub-generation (exception in ScriptApiTracker)

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#212]
To reproduce:

API:

```
@N4JS export external public interface IC {}
@N4JS export external public interface ID extends IC {}


@N4JS export external public abstract class C implements IC {
    public get fetched(): boolean;
}
@N4JS export external public abstract class D extends C implements ID {}
```

Implementation:

```
export public interface IC {
    public get fetched(): boolean {
        return false;
    }
}

export public interface ID extends IC {}


export public abstract class C {} // NOTE: does *not* implement IC!
export public abstract class D extends C implements ID {}
```

If C on implementation side would implement IC, the problem would disappear. Also, if getter "fetched" were added to D (on impl side), the problem would disappear.

Exception:

```
Caused by: java.lang.IllegalStateException
    at eu.numberfour.n4js.ts.types.util.AccessorTuple.setGetter(AccessorTuple.java:97)
    at eu.numberfour.n4js.transpiler.utils.ScriptApiTracker._computeMissingApiGetterSetter(ScriptApiTracker.java:881)
    at eu.numberfour.n4js.transpiler.utils.ScriptApiTracker.computeMissingApiGetterSetter(ScriptApiTracker.java:750)
    at eu.numberfour.n4js.transpiler.utils.ScriptApiTracker.computeMissingApiGetterSetter(ScriptApiTracker.java:732)
    at eu.numberfour.n4js.transpiler.utils.MissingApiMembersForTranspiler.create(MissingApiMembersForTranspiler.java:71)
    at eu.numberfour.n4js.transpiler.es.transform.ApiImplStubGenerationTransformation.createMAMFT(ApiImplStubGenerationTransformation.java:440)
    at eu.numberfour.n4js.transpiler.es.transform.ApiImplStubGenerationTransformation.addMissingMembers(ApiImplStubGenerationTransformation.java:130)
    at eu.numberfour.n4js.transpiler.es.transform.ApiImplStubGenerationTransformation.lambda$0(ApiImplStubGenerationTransformation.java:121)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at eu.numberfour.n4js.transpiler.es.transform.ApiImplStubGenerationTransformation.transform(ApiImplStubGenerationTransformation.java:123)
    at eu.numberfour.n4js.transpiler.AbstractTranspiler.transform(AbstractTranspiler.java:190)
    at eu.numberfour.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:136)
    at eu.numberfour.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:141)
    at eu.numberfour.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:145)
    at eu.numberfour.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:121)
    ... 39 more
```

**Comment by JensN4** [comment]
Should become obsolete with IDE-2337. Check!

**Comment by torstenkraemer** [comment]
Issue is fixed with latest commit
