### ISSUE TITLE
MWE update-site not reachable, update target platform

### ISSUE THREAD

**Issue by torstenkraemer** [NumberFour/n4js#230]
After yesterday's release of Eclipse NEON, we as of today face an unreachable updatesite at http://download.eclipse.org/modeling/emft/mwe/updates/releases/2.8.3

Investigate the source of this outage.
In case of a restructuring on the Eclipse servers update the target platform definition.

```
00:09:35.028 [INFO] Resolving dependencies of MavenProject: eu.numberfour.n4js:eu.numberfour.n4js.releng.utils:0.0.1-SNAPSHOT @ /var/lib/build/workspace/N4JS-PUBLIC/n4js/releng/eu.numberfour.n4js.releng.utils/pom.xml
00:15:19.087 
[ERROR] Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at http://download.eclipse.org/modeling/emft/mwe/updates/releases/2.8.3/site.xml. Read timed out -> [Help 1]
00:15:19.088 org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at http://download.eclipse.org/modeling/emft/mwe/updates/releases/2.8.3/site.xml.
00:15:19.088    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:166)
00:15:19.089    at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132)
00:15:19.090    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by torstenkraemer** [comment]
Update-site seem to be back again.

**Comment by torstenkraemer** [comment]
PUBLIC build went successfully through. Closing this task.
