### ISSUE TITLE
Exception during post-processing of broken AST (illegal forward reference)

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#255]
The following code (with a broken syntax) is causing an exception during post-processing:

```
function foo() {}
foo();

interface
```

Tested in the n4js editor. This is probably unharmful, but should be avoided.

Here the exception:

```
java.lang.Error: forward reference only allowed to identifiable subtrees; but was: eu.numberfour.n4js.n4JS.impl.N4InterfaceDeclarationImpl@1e816128 (declaredModifiers: null, name: null) (typingStrategy: ?~)
    at eu.numberfour.n4js.postprocessing.AbstractProcessor.assertTrueIfRigid(AbstractProcessor.java:261)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree_forwardReference(ASTProcessor.java:234)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.getTypeOfForwardReference(TypeProcessor.java:271)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.getType(TypeProcessor.java:239)
    at eu.numberfour.n4js.typesystem.N4JSTypeSystem.type(N4JSTypeSystem.java:58)
    at eu.numberfour.n4js.typesystem.N4JSTypeSystem.tau(N4JSTypeSystem.java:165)
    at eu.numberfour.n4js.n4JS.extensions.SourceElementExtensions.collectVisibleIdentifiableElement(SourceElementExtensions.java:152)
    at eu.numberfour.n4js.n4JS.extensions.SourceElementExtensions.collectVisibleTypedElement(SourceElementExtensions.java:130)
    at eu.numberfour.n4js.n4JS.extensions.SourceElementExtensions.doCollectVisibleIdentifiableElements(SourceElementExtensions.java:188)
    at eu.numberfour.n4js.n4JS.extensions.SourceElementExtensions.lambda$0(SourceElementExtensions.java:93)
    at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
    at eu.numberfour.n4js.n4JS.extensions.SourceElementExtensions.collectVisibleIdentifiableElements(SourceElementExtensions.java:98)
    at eu.numberfour.n4js.scoping.N4JSScopeProvider.collectLexialEnvironmentsScopeLists(N4JSScopeProvider.java:448)
    at eu.numberfour.n4js.scoping.N4JSScopeProvider.lambda$1(N4JSScopeProvider.java:420)
    at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
    at eu.numberfour.n4js.scoping.N4JSScopeProvider.getLexicalEnvironmentScope(N4JSScopeProvider.java:432)
    at eu.numberfour.n4js.scoping.N4JSScopeProvider.scope_IdentifierRef_id(N4JSScopeProvider.java:395)
    at eu.numberfour.n4js.scoping.N4JSScopeProvider.getScope(N4JSScopeProvider.java:212)
    at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
    at eu.numberfour.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:69)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:247)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
    at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:122)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:243)
    at eu.numberfour.n4js.resource.N4JSResource.doResolveProxy(N4JSResource.java:661)
    at eu.numberfour.n4js.utils.emf.ProxyResolvingEObjectImpl.eResolveProxy(ProxyResolvingEObjectImpl.java:32)
    at eu.numberfour.n4js.n4JS.impl.IdentifierRefImpl.getId(IdentifierRefImpl.java:144)
    at eu.numberfour.n4js.postprocessing.AbstractProcessor.isFparRefInFparDefaultExpression(AbstractProcessor.java:106)
    at eu.numberfour.n4js.postprocessing.AbstractProcessor.askXsemanticsForType(AbstractProcessor.java:85)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:128)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:91)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processNode_postChildren(ASTProcessor.java:296)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:207)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:200)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:200)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:200)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:131)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:113)
    at eu.numberfour.n4js.resource.N4JSPostProcessor.doPerformPostProcessing(N4JSPostProcessor.java:72)
    at eu.numberfour.n4js.resource.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:60)
    at eu.numberfour.n4js.resource.PostProcessingAwareResource.performPostProcessing(PostProcessingAwareResource.java:168)
    at eu.numberfour.n4js.resource.N4JSResource.performPostProcessing(N4JSResource.java:864)
    at eu.numberfour.n4js.resource.PostProcessingAwareResource.resolveLazyCrossReferences(PostProcessingAwareResource.java:120)
    at eu.numberfour.n4js.resource.N4JSResource.resolveLazyCrossReferences(N4JSResource.java:873)
    at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:175)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:153)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:442)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:422)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
    at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:98)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mor-n4** [comment]
here is another piece of code with a similar behavior:

```
class C {
    public [Symbol.iterator]() : Iterator<int> {
        return null;
    }
}

class D implements Iterable<int> {
    @Override
    public [Symbol.iterator]() : Iterator<int> {
        return null;
    }
}

var c = new C();
var d = new D();


// XPECT noerrors -->
for( x of c) {}
// XPECT noerrors -->
for(var x of d) {}
```

minimized version:

```
x;

for(var x of []) {}
```

Exception:

```
java.lang.Error: forward reference only allowed to identifiable subtrees; but was: eu.numberfour.n4js.n4JS.impl.IdentifierRefImpl@1d5ccd3d (strictMode: true, idAsText: d) in
    at eu.numberfour.n4js.postprocessing.AbstractProcessor.assertTrueIfRigid(AbstractProcessor.java:261)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree_forwardReference(ASTProcessor.java:234)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.getTypeOfForwardReference(TypeProcessor.java:271)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.getType(TypeProcessor.java:239)
    at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.typeInternal(CustomInternalTypeSystem.java:177)
    at eu.numberfour.n4js.xsemantics.InternalTypeSystem.applyRuleTypeVariableDeclaration(InternalTypeSystem.java:3289)
    at eu.numberfour.n4js.xsemantics.InternalTypeSystem.typeImpl(InternalTypeSystem.java:3208)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:296)
    at eu.numberfour.n4js.xsemantics.InternalTypeSystem.typeInternal(InternalTypeSystem.java:791)
    at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.use_type_judgment_from_PostProcessors(CustomInternalTypeSystem.java:189)
    at eu.numberfour.n4js.postprocessing.AbstractProcessor.askXsemanticsForType(AbstractProcessor.java:97)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:128)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:91)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processNode_postChildren(ASTProcessor.java:296)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:207)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree_forwardReference(ASTProcessor.java:276)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.getTypeOfForwardReference(TypeProcessor.java:271)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.getType(TypeProcessor.java:239)
    at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.typeInternal(CustomInternalTypeSystem.java:177)
    at eu.numberfour.n4js.xsemantics.InternalTypeSystem.applyRuleTypeIdentifierRef(InternalTypeSystem.java:1350)
    at eu.numberfour.n4js.xsemantics.InternalTypeSystem.typeImpl(InternalTypeSystem.java:1330)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:296)
    at eu.numberfour.n4js.xsemantics.InternalTypeSystem.typeInternal(InternalTypeSystem.java:791)
    at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.use_type_judgment_from_PostProcessors(CustomInternalTypeSystem.java:189)
    at eu.numberfour.n4js.postprocessing.AbstractProcessor.askXsemanticsForType(AbstractProcessor.java:97)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:128)
    at eu.numberfour.n4js.postprocessing.TypeProcessor.typeNode(TypeProcessor.java:91)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processNode_postChildren(ASTProcessor.java:296)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:207)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:200)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:200)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:131)
    at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:113)
    at eu.numberfour.n4js.resource.N4JSPostProcessor.doPerformPostProcessing(N4JSPostProcessor.java:72)
    at eu.numberfour.n4js.resource.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:60)
    at eu.numberfour.n4js.resource.PostProcessingAwareResource.performPostProcessing(PostProcessingAwareResource.java:168)
    at eu.numberfour.n4js.resource.N4JSResource.performPostProcessing(N4JSResource.java:864)
    at eu.numberfour.n4js.resource.PostProcessingAwareResource.resolveLazyCrossReferences(PostProcessingAwareResource.java:120)
    at eu.numberfour.n4js.resource.N4JSResource.resolveLazyCrossReferences(N4JSResource.java:873)
    at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:175)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:153)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:442)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:422)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
    at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:98)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by kduske-n4** [comment]
When running the n4ide spec tests locally:

```
63633 [main] ERROR eu.numberfour.n4js.ui.building.instructions.BuildInstruction  - Error during compilation of 'platform:/resource/P1/src/a/c/GH166_C.n4js.xt'.
eu.numberfour.n4js.generator.common.GeneratorException: Severe error occurred in transpiler=es message=Rewire() called for an proxified original target. IM-eobject = null (dynamic: false) (arrayTypeLiteral: false, definedTypingStrategy: ?~)   origTarget is eu.numberfour.n4js.ts.types.impl.TypeImpl@6f80c826 (eProxyURI: platform:/resource/P1/src/a/c/GH166_C.n4js.xt#|1).
    at eu.numberfour.n4js.generator.common.ExceptionHandler.handleError(ExceptionHandler.java:21)
    at eu.numberfour.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:174)
    at eu.numberfour.n4js.generator.CompositeGenerator.lambda$0(CompositeGenerator.java:88)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
    at eu.numberfour.n4js.generator.CompositeGenerator.useTranspilerType(CompositeGenerator.java:86)
    at eu.numberfour.n4js.generator.CompositeGenerator.doGenerate(CompositeGenerator.java:62)
    at eu.numberfour.n4js.ui.building.instructions.BuildInstruction.handleChangedContents(BuildInstruction.java:200)
    at eu.numberfour.n4js.ui.building.instructions.BuildInstruction.process(BuildInstruction.java:128)
    at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:222)
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
    at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:191)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
    at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
    at eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
    at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
    at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
    at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
    at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
    at org.xpect.xtext.lib.setup.workspace.Workspace.buildIncrementally(Workspace.java:70)
    at org.xpect.xtext.lib.setup.XtextWorkspaceSetup.getInstance(XtextWorkspaceSetup.java:69)
    at org.xpect.xtext.lib.setup.XtextWorkspaceSetup.createThisResource(XtextWorkspaceSetup.java:88)
    at sun.reflect.GeneratedMethodAccessor419.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.xpect.state.StateContainer.createInstance(StateContainer.java:176)
    at org.xpect.state.StateContainer.createInstance(StateContainer.java:198)
    at org.xpect.state.StateContainer.get(StateContainer.java:248)
    at org.xpect.state.StateContainer.get(StateContainer.java:210)
    at org.xpect.state.StateContainer.createFactory(StateContainer.java:150)
    at org.xpect.state.StateContainer.getFactory(StateContainer.java:271)
    at org.xpect.state.StateContainer.createInstance(StateContainer.java:174)
    at org.xpect.state.StateContainer.createInstance(StateContainer.java:198)
    at org.xpect.state.StateContainer.get(StateContainer.java:248)
    at org.xpect.state.StateContainer.get(StateContainer.java:210)
    at org.xpect.runner.XpectFileRunner.run(XpectFileRunner.java:155)
    at org.xpect.runner.XpectRunner.runChild(XpectRunner.java:231)
    at org.xpect.runner.XpectRunner.runChild(XpectRunner.java:1)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.xpect.runner.XpectRunner.run(XpectRunner.java:217)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:66)
    at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:43)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at eu.numberfour.n4js.product.N4JSApplication.start(N4JSApplication.java:141)
    at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:52)
    at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:43)
    at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:46)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.IllegalStateException: Rewire() called for an proxified original target. IM-eobject = null (dynamic: false) (arrayTypeLiteral: false, definedTypingStrategy: ?~)   origTarget is eu.numberfour.n4js.ts.types.impl.TypeImpl@6f80c826 (eProxyURI: platform:/resource/P1/src/a/c/GH166_C.n4js.xt#|1)
    at eu.numberfour.n4js.transpiler.PreparationStep$AST2IMCopier.rewire(PreparationStep.java:278)
    at eu.numberfour.n4js.transpiler.PreparationStep$AST2IMCopier.copyReference(PreparationStep.java:222)
    at org.eclipse.emf.ecore.util.EcoreUtil$Copier.copyReferences(EcoreUtil.java:688)
    at eu.numberfour.n4js.transpiler.PreparationStep.createIM(PreparationStep.java:90)
    at eu.numberfour.n4js.transpiler.PreparationStep.prepare(PreparationStep.java:79)
    at eu.numberfour.n4js.transpiler.AbstractTranspiler.prepare(AbstractTranspiler.java:150)
    at eu.numberfour.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:133)
    at eu.numberfour.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:141)
    at eu.numberfour.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:145)
    at eu.numberfour.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:121)
    ... 99 more
```
