### ISSUE TITLE
Resolve IllegalStateException in calls to ClusteringBuilderState from ExternalLibraryBuilderHelper

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#295]
During our tests with ExternalLibraries there are exceptions logged, but they don't disrupt build process.
Looks like it is because of ```getReferenceDescriptions``` and ```getImportedNames``` gets called on ```CopiedResourceDescription```. Following [xtext bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=344373) suggests that those kid of the resources should not end up in the index. 

```
36153 [Worker-3] ERROR org.eclipse.xtext.builder.clustering.CopiedResourceDescription  - java.lang.IllegalStateException: getReferenceDescriptions file:/var/lib/build/workspace/N4JS/n4js/tests/eu.numberfour.n4js.ui.tests/probands/IDE_1977_ExternalLibs/PD/src/D.n4js
java.lang.IllegalStateException: getReferenceDescriptions file:/var/lib/build/workspace/N4JS/n4js/tests/eu.numberfour.n4js.ui.tests/probands/IDE_1977_ExternalLibs/PD/src/D.n4js
	at org.eclipse.xtext.builder.clustering.CopiedResourceDescription.getReferenceDescriptions(CopiedResourceDescription.java:84)
	at org.eclipse.xtext.builder.builderState.BuilderStateUtil.copyReferenceDescriptions(BuilderStateUtil.java:59)
	at org.eclipse.xtext.builder.builderState.BuilderStateUtil.create(BuilderStateUtil.java:34)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:267)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:191)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.run(ExternalLibraryBuilderHelper.java:426)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.access$3(ExternalLibraryBuilderHelper.java:378)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.doPerformOperation(ExternalLibraryBuilderHelper.java:276)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:173)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:149)
	at eu.numberfour.n4js.external.ExternalLibraryBuildJobProvider$ExternalLibraryBuildJob.runInWorkspace(ExternalLibraryBuildJobProvider.java:79)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

```
36154 [Worker-3] ERROR org.eclipse.xtext.builder.clustering.CopiedResourceDescription  - java.lang.IllegalStateException: getImportedNames file:/var/lib/build/workspace/N4JS/n4js/tests/eu.numberfour.n4js.ui.tests/probands/IDE_1977_ExternalLibs/PD/src/D.n4js
java.lang.IllegalStateException: getImportedNames file:/var/lib/build/workspace/N4JS/n4js/tests/eu.numberfour.n4js.ui.tests/probands/IDE_1977_ExternalLibs/PD/src/D.n4js
	at org.eclipse.xtext.builder.clustering.CopiedResourceDescription.getImportedNames(CopiedResourceDescription.java:75)
	at org.eclipse.xtext.builder.builderState.BuilderStateUtil.copyImportedNames(BuilderStateUtil.java:40)
	at org.eclipse.xtext.builder.builderState.BuilderStateUtil.create(BuilderStateUtil.java:35)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:267)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:191)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.run(ExternalLibraryBuilderHelper.java:426)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.access$3(ExternalLibraryBuilderHelper.java:378)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.doPerformOperation(ExternalLibraryBuilderHelper.java:276)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:173)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:149)
	at eu.numberfour.n4js.external.ExternalLibraryBuildJobProvider$ExternalLibraryBuildJob.runInWorkspace(ExternalLibraryBuildJobProvider.java:79)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by yoosiba** [comment]
@meysholdt Could you ask me in proper direction?

**Comment by meysholdt** [comment]
hey Jakub,

I can reproduce this by adding a conditional breakpoint to 
`org.eclipse.xtext.resource.impl.ResourceDescriptionsData.registerDescription(IResourceDescription, Map<QualifiedName, Object>)` with condition `description.getClass().getName().contains("Copied")` and running eu.numberfour.n4js.tests.externalPackages.RunExternalLibrariesPluginTest.

This leads to the stack trace:

```
at org.eclipse.xtext.resource.impl.ResourceDescriptionsData.registerDescription(ResourceDescriptionsData.java:215)
    at org.eclipse.xtext.resource.impl.ResourceDescriptionsData.addDescription(ResourceDescriptionsData.java:209)
    at org.eclipse.xtext.resource.impl.ResourceDescriptionsData.register(ResourceDescriptionsData.java:245)
    at org.eclipse.xtext.builder.clustering.CurrentDescriptions.register(CurrentDescriptions.java:83)
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.writeNewResourceDescriptions(ClusteringBuilderState.java:401)
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:135)
    at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:191)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.run(ExternalLibraryBuilderHelper.java:426)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.access$3(ExternalLibraryBuilderHelper.java:378)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.doPerformOperation(ExternalLibraryBuilderHelper.java:276)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:173)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:161)
    at eu.numberfour.n4js.external.EclipseExternalLibraryWorkspace.storeUpdated(EclipseExternalLibraryWorkspace.java:281)
    at eu.numberfour.n4js.preferences.ExternalLibraryPreferenceStoreImpl.notifyListeners(ExternalLibraryPreferenceStoreImpl.java:146)
    at eu.numberfour.n4js.preferences.ExternalLibraryPreferenceStoreImpl.save(ExternalLibraryPreferenceStoreImpl.java:92)
    at eu.numberfour.n4js.tests.externalPackages.RunExternalLibrariesPluginTest.setupWorkspace(RunExternalLibrariesPluginTest.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62)
    at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness$1.run(PlatformUITestHarness.java:47)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:54)
    at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:47)
    at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

I haven't looked deeper into that stack trace yet. Do you spot something?

**Comment by yoosiba** [comment]
I see

```
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.writeNewResourceDescriptions(ClusteringBuilderState.java:401)
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:135)
    at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:191)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
```

so our builder gets `DefaultResourceDescription`, but then delegates to super class and `ClusteringBuilderState.writeNewResourceDescriptions` puts `CopiedResourceDescription` into the delta processed later by the builder:

``` java
                    if (manager != null) {
                        // We don't care here about links, we really just want the exported objects so that we can link in the
                        // next phase.
                        final IResourceDescription description = manager.getResourceDescription(resource);
                        final IResourceDescription copiedDescription = new CopiedResourceDescription(description);
                        // We also don't care what kind of Delta we get here; it's just a temporary transport vehicle. That interface
                        // could do with some clean-up, too, because all we actually want to do is register the new resource
                        // description, not the delta.
                        newState.register(new DefaultResourceDescriptionDelta(oldState.getResourceDescription(uri), copiedDescription));
                        buildData.queueURI(uri);
                    }
```

I could override in our builder, but I don't understand that. Are we using xtext builder in the wrong way (i.e. wrong input)?

Or access to data obtained from the original should be allowed in the copy? i.e. change in 

``` java
    @Override
    public Iterable<QualifiedName> getImportedNames() {
        // TODO see https://bugs.eclipse.org/bugs/show_bug.cgi?id=344373
        IllegalStateException exception = new IllegalStateException("getImportedNames "+getURI());
        log.error(exception, exception);
        return Collections.emptyList();
//        throw new UnsupportedOperationException("getImportedNames()");
    }
```

**Comment by yoosiba** [comment]
I will need to see if it happens in the product and actual N4JS projects. Maybe it is just this test setup / test data. I will investigate next week. Weather is too nice to do it now :)
Have a nice weekend.

**Comment by yoosiba** [comment]
I have found a bit more about the issue. At this point I can work around it, but I am not sure if there is nothing to follow up.
In the product we have two workspaces, one normal (i.e. eclipse workspace), other external workspace for (external) projects user doesn't have that much control. Something like target platform from eclipse - you can add / remove their projects as workspace wide dependencies. There is custom logic assuring that workspace projects take precedence over external ones. For example assume you have project `PA` in your workspace (let's call it `wsPA`) and exact copy of that project in external workspace (let's call it `exPA`). Then if you have project `Client` in your workspace, with depends on `PA`, then dependency is resolved to `wsPA`. If you delete / close workspace version of `PA`, then dependency is resolved to `exPA`.

This bug occurs in tests for that behaviour. Assume chain of projects that depends on each other `PA<-PB<-PC<-PD` and client `PD<-Client`. In the test we have workspace copies of projects `wsA<-wsB<-wsC<-wsD` and their external copies `exPA<-exPB<-exPC<-exPD` Effective dependencies of the client are `wsPA<-wsPB<-wsPC<-wsPD<-Client`.
Now what we try to test is that if you close / delete from workspace `wsPB, wsPD` then client effective dependencies become `wsPA<-exPB<-wsPC<-exPD<-Client`.
The way we test is doing the deletion, causes the exception.
if we do 

``` java
        for (final String libProjectName : newArrayList(PB, PD)) {
            getProjectByName(libProjectName).delete(true, new NullProgressMonitor());
        }
        waitForAutoBuild();
        cleanBuild();
        waitForAutoBuild();
```

we get exception, if we do 

``` java
        for (final String libProjectName : newArrayList(PB, PD)) {
            getProjectByName(libProjectName).delete(true, new NullProgressMonitor());
            waitForAutoBuild();
            cleanBuild();
            waitForAutoBuild();
        }
```

we get no exception. Performing a clean build here is essential, as we do get exception if we do just

``` java
        for (final String libProjectName : newArrayList(PB, PD)) {
            getProjectByName(libProjectName).delete(true, new NullProgressMonitor());
            waitForAutoBuild();
        }
```

Workaround for test is obvious, i will adjust the test to wait.
But I need to understand assumptions of `org.eclipse.xtext.builder.clustering.ClusteringBuilderState` to avoid this kind of issues in the future. 
Clustering builder will fall into catch block (line 244) with exception `org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.core.internal.resources.ResourceException: Resource '/PB/src/B.n4js' does not exist`. This in turn causes it to create `CopiedResourceDescription` in line 267 and then put it into the `newDelta`.

@meysholdt 
Can we avoid it without extra synchronisations on build job? Maybe in our builder we could do some preprocessing to adjust what is in the `buildData` or `newDelta` ?

P.S. Why exceptions thrown are used as control flow in clustering builder? Would it be possible to check assumptions before and adjust next steps, instead recovering in catch? For large workspaces it seems bad idea to go through try-catch... Builder seems a bit to important for this approach...

**Comment by yoosiba** [comment]
workaround applied with a589697
