### ISSUE TITLE
Resolve concurrent modification exception in builds

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#296]
in our build logs we can see following exception
```
79064 [main] INFO  eu.numberfour.n4js.external.ExternalLibraryBuilderHelper  - Building external library: eu.numberfour.mangelhaft.assert
79065 [Worker-1] ERROR eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder  - Error in n4js-build
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:149)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:191)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
	at eu.numberfour.n4js.external.RebuildWorkspaceProjectsJob.runInWorkspace(RebuildWorkspaceProjectsJob.java:61)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by kduske-n4** [comment]
Dis gun be good.

**Comment by kduske-n4** [comment]
In my builds, I see the same exception but with a slightly different stack trace:

```
728791 [WorkbenchTestable] ERROR eu.numberfour.n4js.external.ExternalLibraryBuilderHelper  - Error occurred while building external library bignumber.js.
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
    at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
    at com.google.common.base.Joiner.appendTo(Joiner.java:109)
    at com.google.common.base.Joiner.appendTo(Joiner.java:152)
    at com.google.common.collect.Iterators.toString(Iterators.java:283)
    at com.google.common.collect.Iterables.toString(Iterables.java:275)
    at com.google.common.collect.FluentIterable.toString(FluentIterable.java:118)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.logBuildData(N4JSGenerateImmediatelyBuilderState.java:208)
    at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:174)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.run(ExternalLibraryBuilderHelper.java:426)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.access$3(ExternalLibraryBuilderHelper.java:378)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.doPerformOperation(ExternalLibraryBuilderHelper.java:276)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:173)
    at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:161)
    at eu.numberfour.n4js.external.EclipseExternalLibraryWorkspace.registerProjects(EclipseExternalLibraryWorkspace.java:329)
    at eu.numberfour.n4js.external.NpmManager.installDependency(NpmManager.java:234)
    at eu.numberfour.n4js.n4.tests.realworld.FabelhaftSnapshotIntegrationPluginTestLowMemory.downloadNpmDependencies(FabelhaftSnapshotIntegrationPluginTestLowMemory.java:196)
    at eu.numberfour.n4js.n4.tests.realworld.FabelhaftSnapshotIntegrationPluginTestLowMemory.configureBuiltIns(FabelhaftSnapshotIntegrationPluginTestLowMemory.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
    at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
    at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
    at java.lang.Thread.run(Thread.java:745)
```
