### ISSUE TITLE
Investigate NullPointerException in StatusHandlerRegistry in our builds

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#297]
In our builds we can see NPE:
```
!ENTRY org.eclipse.core.resources 2 10035 2016-11-08 12:00:33.190
!MESSAGE The workspace will exit with unsaved changes in this session.

!ENTRY org.eclipse.core.resources 2 10035 2016-11-08 12:00:33.193
!MESSAGE The workspace will exit with unsaved changes in this session.

!ENTRY org.eclipse.ui 4 0 2016-11-08 12:00:33.194
!MESSAGE Error occurred during status handling
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.addExtension(StatusHandlerRegistry.java:104)
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.<init>(StatusHandlerRegistry.java:69)
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.getDefault(StatusHandlerRegistry.java:91)
	at org.eclipse.ui.statushandlers.StatusManager.getStatusHandler(StatusManager.java:135)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:189)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:231)
	at org.eclipse.ui.statushandlers.StatusManager$StatusManagerLogListener.logging(StatusManager.java:302)
	at org.eclipse.core.internal.runtime.RuntimeLog.logToListeners(RuntimeLog.java:161)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:103)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:88)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:217)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:189)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:65)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceImpl.log(ExtendedLogServiceImpl.java:87)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:54)
	at org.eclipse.core.internal.runtime.Log.log(Log.java:65)
	at org.eclipse.core.internal.utils.Policy.log(Policy.java:159)
	at org.eclipse.core.internal.resources.SaveManager.reportSnapshotRequestor(SaveManager.java:657)
	at org.eclipse.core.internal.resources.Workspace.close(Workspace.java:575)
	at org.eclipse.core.resources.ResourcesPlugin.stop(ResourcesPlugin.java:434)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:830)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:823)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:946)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:314)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1580)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:253)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:147)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:191)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yoosiba** [comment]
One solution is to ensure logger is properly initiated to avoid NPE. In this case it would be also nice if it would be logger that just intercepts logs but does not write them anywhere (console / file, etc.).

Other approach is to look into `org.eclipse.core.tests.resources.ResourceTest.cleanup()` as mentioned in the https://bugs.eclipse.org/bugs/show_bug.cgi?id=448097

**Comment by yoosiba** [comment]
In all tests that have this issue use dedicated utility `EclipseGracefulUIShutdownEnabler`
Calling it once early in the test will initialise the logger which makes `NPE` disappear.
