### ISSUE TITLE
RTE when trying to run a module from a runtime library

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#30]
IDEBUG-405
 Open any n4js or n4jsd file from a runtime library in editor: for instance DepRegistry from runtime.n4. Right click in the editor area, select run as... no submenus are available, click anywhere to close context menu shell. Got:

```

!ENTRY org.eclipse.ui 4 0 2015-05-19 16:24:07.667
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.RuntimeException: Cannot resolve execution environment for the project runtime.n4 of type RUNTIME_LIBRARY
    at eu.numberfour.ide.runner.RuntimeEnvironmentsHelper.findProjectEnvironments(RuntimeEnvironmentsHelper.java:55)
    at eu.numberfour.ide.runner.ui.SupportingRunnerPropertyTester.resolveRequiredEnvironments(SupportingRunnerPropertyTester.java:168)
    at eu.numberfour.ide.runner.ui.SupportingRunnerPropertyTester.resolveRequiredEnvironments(SupportingRunnerPropertyTester.java:140)
    at eu.numberfour.ide.runner.ui.SupportingRunnerPropertyTester.dipatchResolveRequiredEnvironments(SupportingRunnerPropertyTester.java:124)
    at eu.numberfour.ide.runner.ui.SupportingRunnerPropertyTester.test(SupportingRunnerPropertyTester.java:82)
    at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
    at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:99)
    at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
    at org.eclipse.core.internal.expressions.AndExpression.evaluate(AndExpression.java:29)
    at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
    at org.eclipse.core.internal.expressions.IterateExpression.evaluate(IterateExpression.java:150)
    at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
    at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:72)
    at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
    at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:53)
    at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.evalEnablementExpression(LaunchShortcutExtension.java:281)
    at org.eclipse.debug.ui.actions.ContextualLaunchAction.isApplicable(ContextualLaunchAction.java:287)
    at org.eclipse.debug.ui.actions.ContextualLaunchAction.fillMenu(ContextualLaunchAction.java:218)
    at org.eclipse.debug.ui.actions.ContextualLaunchAction$1.menuShown(ContextualLaunchAction.java:141)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:255)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
    at org.eclipse.jface.action.ActionContributionItem.copyMenu(ActionContributionItem.java:1276)
    at org.eclipse.jface.action.ActionContributionItem.handleShowProxy(ActionContributionItem.java:1256)
    at org.eclipse.jface.action.ActionContributionItem.access$4(ActionContributionItem.java:1245)
    at org.eclipse.jface.action.ActionContributionItem$8.handleEvent(ActionContributionItem.java:1218)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1471)
    at org.eclipse.swt.widgets.Menu.menuWillOpen(Menu.java:806)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5692)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSMenu.popUpContextMenu(NSMenu.java:77)
    at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:278)
    at org.eclipse.swt.widgets.Display.runPopups(Display.java:4119)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at eu.numberfour.ide.product.N4Application.start(N4Application.java:137)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

```

The problem is most likely in the {{SupportingRunnerPropertyTester}}.

**Comment by mor-n4** [comment]
probably related: #50

**Comment by mor-n4** [comment]
closing this as duplicate (of #50)
