### ISSUE TITLE
References from n4js to n4jsx files causing havoc (sometimes)

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#324]
To reproduce, create an N4JS project with the following two files:
```
// foo.n4js

import { baz } from "bar";

console.log('hello from foo.n4js');
console.log(baz);


export public function getMessage(): string {
	return "hello";
}
```
and
```
// bar.n4jsx

import { getMessage } from "foo";

export public const baz = <div align="center">{getMessage()}</div>;
```
In addition, you need a third file `react.n4jsd` (as usual with n4jsx).

Now:
1. close all editors and perform a clean build
2. open `bar.n4jsx`
3. hover the mouse over the call expression `getMessage()` in the last line until the tool tip shows up
4. add an empty line at the end (to get editor in dirty state) & save the file

This will throw exceptions during post-processing (when touching and saving file `bar.n4jsx`):
```
java.lang.RuntimeException: exception while post-processing resource platform:/resource/TestN4JSX_Transpiler/src/bar.n4jsx
	at eu.numberfour.n4js.resource.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:69)
	at eu.numberfour.n4js.resource.PostProcessingAwareResource.performPostProcessing(PostProcessingAwareResource.java:168)
	at eu.numberfour.n4js.resource.N4JSResource.performPostProcessing(N4JSResource.java:862)
	at eu.numberfour.n4js.resource.PostProcessingAwareResource.resolveLazyCrossReferences(PostProcessingAwareResource.java:120)
	at eu.numberfour.n4js.resource.N4JSResource.resolveLazyCrossReferences(N4JSResource.java:871)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.resolveProxies(ResourceValidatorImpl.java:161)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:74)
	at eu.numberfour.n4js.ui.validation.ManifestAwareResourceValidator.validate(ManifestAwareResourceValidator.java:43)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:98)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.RuntimeException: exception while post-processing resource platform:/resource/TestN4JSX_Transpiler/src/foo.n4js
	at eu.numberfour.n4js.resource.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:69)
	at eu.numberfour.n4js.resource.PostProcessingAwareResource.performPostProcessing(PostProcessingAwareResource.java:168)
	at eu.numberfour.n4js.resource.N4JSResource.performPostProcessing(N4JSResource.java:862)
	at eu.numberfour.n4js.resource.PostProcessingAwareResource.performPostProcessing(PostProcessingAwareResource.java:127)
	at eu.numberfour.n4js.postprocessing.TypeProcessor.getType(TypeProcessor.java:213)
	at eu.numberfour.n4js.typesystem.N4JSTypeSystem.type(N4JSTypeSystem.java:58)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processNode_postChildren(ASTProcessor.java:308)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:212)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:205)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processSubtree(ASTProcessor.java:205)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:136)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:118)
	at eu.numberfour.n4js.resource.N4JSPostProcessor.doPerformPostProcessing(N4JSPostProcessor.java:77)
	at eu.numberfour.n4js.resource.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:61)
	... 18 more
Caused by: java.lang.IllegalStateException: multiple invocation of method ASTMetaInfoCache#startProcessing()
	at eu.numberfour.n4js.postprocessing.ASTMetaInfoCache.startProcessing(ASTMetaInfoCache.java:195)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:133)
	at eu.numberfour.n4js.postprocessing.ASTProcessor.processAST(ASTProcessor.java:118)
	at eu.numberfour.n4js.resource.N4JSPostProcessor.doPerformPostProcessing(N4JSPostProcessor.java:77)
	at eu.numberfour.n4js.resource.N4JSPostProcessor.performPostProcessing(N4JSPostProcessor.java:61)
	... 31 more
```

**Comment by mor-n4** [comment]
After looking into this some more, here a simpler example to reproduce the exceptions:
```
// foo.n4js

import { baz } from "bar";

console.log('hello from foo.n4js');
console.log(baz);
```
and
```
// bar.n4jsx

export public const baz = <div/>;
```

Now:
1. close all editors and perform a clean build
2. open `foo.n4js`
3. hover the mouse over the identifier `baz` in the import statement until the tool tip shows up
4. add an empty line at the end (to get editor into dirty state) & save the file

Throws same exception as above.

So, a *cyclic* reference is not required. I have adjusted the title to reflect this but kept the original example in the task description for reference.

**Comment by yoosiba** [comment]
cannot reproduce in https://github.com/eclipse/n4js
