### ISSUE TITLE
Xpect files in IDE throwing exceptions

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#357]
Some of our Xpect test files work properly when run as a junit test using the Xpect runner (e.g. in our nightly build or when run locally) but throw exceptions when copied into the N4JS IDE (i.e. the product).

Examples of such files are:

* `SuperGetterSetterAccess_remote.n4js.xt` from `eu.numberfour.n4js.spec.tests`
* `IDE_1789_CyclicDependencies_Test.n4js.xt` from `eu.numberfour.n4js.bugreports.tests`

To reproduce: copy one of the above test files together with its required imported files into the work space, making sure that all folders are set up properly to ensure the imports can be resolved, and then perform a clean build or open the `.xt` file in an Xpect+Xtext editor.

The exceptions occur when the file is processed by the incremental builder as well as when it is opened in an Xpect+Xtext editor. However, when opened in a plain N4JS editor or when the `.xt` file extension is removed from the file name, the exceptions no longer occur (so it seems to be a problem of the Xpect support in the IDE).

Sample stack trace:
```
java.lang.NullPointerException
	at org.xpect.scoping.ComponentUtil.getValidRootTypes(ComponentUtil.java:80)
	at org.xpect.scoping.ComponentUtil.getValidTypes(ComponentUtil.java:107)
	at org.xpect.scoping.XpectScopeProvider.getAssignableTypes(XpectScopeProvider.java:63)
	at org.xpect.scoping.XpectScopeProvider.getScopeForComponentClass(XpectScopeProvider.java:114)
	at org.xpect.scoping.XpectScopeProvider.getScope(XpectScopeProvider.java:94)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:119)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:247)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doResolveLazyCrossReference(LazyLinkingResource.java:189)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReference(LazyLinkingResource.java:148)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReferences(LazyLinkingResource.java:134)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.resolveProxies(ResourceValidatorImpl.java:161)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:74)
	at org.xpect.ui.services.XtResourceValidator.validateXpect(XtResourceValidator.java:60)
	at org.xpect.ui.services.XtResourceValidator.validate(XtResourceValidator.java:42)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.addMarkers(DefaultResourceUIValidatorExtension.java:60)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.updateValidationMarkers(DefaultResourceUIValidatorExtension.java:46)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:93)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:63)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:82)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:220)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:188)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder.incrementalBuild(N4JSBuildTypeTrackingBuilder.java:54)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/553
