### ISSUE TITLE
'prototype' is not a valid value for a computed property name

### ISSUE THREAD

**Issue by kduske-n4** [NumberFour/n4js#364]
See http://build-master.corp.numberfour.eu:8080/view/N4JS/job/N4JS_nightly_II/204/eu.numberfour.n4js$eu.numberfour.n4js.tests.ecmatestsuite/console

```
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    generators that are named "prototype" throw a TypeError
---*/
assert.throws(TypeError, function() {
  class C {
    static *['prototype']() {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/generator-prototype.js]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at eu.numberfour.n4js.analysis.NegativeAnalyser.analyse(NegativeAnalyser.java:59)
	at eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite.test(ECMA6TestSuite.java:135)

testtest/language/computed-property-names/class/static/getter-prototype.js(eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite)  Time elapsed: 0.032 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected errors in test/language/computed-property-names/class/static/getter-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    getters that are named "prototype" throw a TypeError
---*/
assert.throws(TypeError, function() {
  class C {
    static get ['prototype']() {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/getter-prototype.js]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at eu.numberfour.n4js.analysis.NegativeAnalyser.analyse(NegativeAnalyser.java:59)
	at eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite.test(ECMA6TestSuite.java:135)

testtest/language/computed-property-names/class/static/method-prototype.js(eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite)  Time elapsed: 0.027 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected errors in test/language/computed-property-names/class/static/method-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    methods that are named "prototype" throw a TypeError
---*/

assert.throws(TypeError, function() {
  class C {
    static ['prototype']() {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/method-prototype.js]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at eu.numberfour.n4js.analysis.NegativeAnalyser.analyse(NegativeAnalyser.java:59)
	at eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite.test(ECMA6TestSuite.java:135)

testtest/language/computed-property-names/class/static/setter-prototype.js(eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite)  Time elapsed: 0.025 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected errors in test/language/computed-property-names/class/static/setter-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    setters that are named "prototype" throw a TypeError
---*/

assert.throws(TypeError, function() {
  class C {
    static set ['prototype'](x) {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/setter-prototype.js]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at eu.numberfour.n4js.analysis.NegativeAnalyser.analyse(NegativeAnalyser.java:59)
	at eu.numberfour.n4js.tests.ecmatestsuite.ECMA6TestSuite.test(ECMA6TestSuite.java:135)

Running eu.numberfour.n4js.tests.ecmatestsuite.ECMA5HighlightingTestSuite
Tests run: 11751, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.452 sec - in eu.numberfour.n4js.tests.ecmatestsuite.ECMA5HighlightingTestSuite
Running eu.numberfour.n4js.tests.ecmatestsuite.ECMA6HighlightingTestSuite
Tests run: 15054, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 51.364 sec - in eu.numberfour.n4js.tests.ecmatestsuite.ECMA6HighlightingTestSuite

Results :

Failed tests: 
  ECMA6TestSuite.test:135 expected errors in test/language/computed-property-names/class/static/generator-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    generators that are named "prototype" throw a TypeError
---*/
assert.throws(TypeError, function() {
  class C {
    static *['prototype']() {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/generator-prototype.js]>
  ECMA6TestSuite.test:135 expected errors in test/language/computed-property-names/class/static/getter-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    getters that are named "prototype" throw a TypeError
---*/
assert.throws(TypeError, function() {
  class C {
    static get ['prototype']() {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/getter-prototype.js]>
  ECMA6TestSuite.test:135 expected errors in test/language/computed-property-names/class/static/method-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    methods that are named "prototype" throw a TypeError
---*/

assert.throws(TypeError, function() {
  class C {
    static ['prototype']() {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/method-prototype.js]>
  ECMA6TestSuite.test:135 expected errors in test/language/computed-property-names/class/static/setter-prototype.js but there was not a single one expected:<[// Copyright (C) 2014 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
es6id: 14.5.14
description: >
    In a class, computed property names for static
    setters that are named "prototype" throw a TypeError
---*/

assert.throws(TypeError, function() {
  class C {
    static set ['prototype'](x) {}
  }
});
]> but was:<[test/language/computed-property-names/class/static/setter-prototype.js]>

Tests run: 53610, Failures: 4, Errors: 0, Skipped: 0
```

**Comment by kduske-n4** [comment]
Turns out the validation is done in `ASTStructureValidator`, which runs before AST processing takes place. Computed property names are evaluated and set during AST processing, so the name is not available when the validation attempts to check it.

**Comment by kduske-n4** [comment]
As a first measure, I have disabled the failing Ecmascript tests. Since computed property names are evaluated during resource processing, they cannot be validated for plain JS files anymore. But I have added a few tests for this particular case to the our spec tests and added a validation to N4JSNameValidator to catch the problem at least for N4JS files.
