### ISSUE TITLE
Transpiler error when compiling expression with stray boolean operator

### ISSUE THREAD

**Issue by kduske-n4** [NumberFour/n4js#374]
The following code causes the transpiler to run into a severe error.

```javascript
function m() {
	let valid = true && true &&
	return valid;
}
```

Note the stray boolean AND operator at the end of the boolean expression. If that is removed, all is well.

Problem view says

> Severe error occurred while transpiling module A. Check error log for details about the failure.

Error log:

```
eu.numberfour.n4js.generator.common.GeneratorException: Severe error occurred in transpiler=es message=element to process may not be null.
	at eu.numberfour.n4js.generator.common.ExceptionHandler.handleError(ExceptionHandler.java:21)
	at eu.numberfour.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:180)
	at eu.numberfour.n4js.generator.CompositeGenerator.lambda$0(CompositeGenerator.java:88)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at eu.numberfour.n4js.generator.CompositeGenerator.useTranspilerType(CompositeGenerator.java:86)
	at eu.numberfour.n4js.generator.CompositeGenerator.doGenerate(CompositeGenerator.java:62)
	at eu.numberfour.n4js.ui.building.instructions.BuildInstruction.handleChangedContents(BuildInstruction.java:200)
	at eu.numberfour.n4js.ui.building.instructions.BuildInstruction.process(BuildInstruction.java:128)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.updateMarkers(N4JSGenerateImmediatelyBuilderState.java:228)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:188)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:77)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at eu.numberfour.n4js.ui.building.N4JSBuildTypeTrackingBuilder.incrementalBuild(N4JSBuildTypeTrackingBuilder.java:54)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.IllegalArgumentException: element to process may not be null
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1003)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBinaryExpression(PrettyPrinterSwitch.java:1138)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBinaryLogicalExpression(PrettyPrinterSwitch.java:902)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBinaryLogicalExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:1274)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseVariableDeclaration(PrettyPrinterSwitch.java:373)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseVariableDeclaration(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:460)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:978)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseVariableStatement(PrettyPrinterSwitch.java:330)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseVariableStatement(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:416)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:988)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBlockLike(PrettyPrinterSwitch.java:1121)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBlock(PrettyPrinterSwitch.java:1104)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBlock(PrettyPrinterSwitch.java:322)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBlock(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:394)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseFunctionExpression(PrettyPrinterSwitch.java:279)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseFunctionExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:334)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBinaryExpression(PrettyPrinterSwitch.java:1138)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseAssignmentExpression(PrettyPrinterSwitch.java:908)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseAssignmentExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:1290)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseExpressionStatement(PrettyPrinterSwitch.java:392)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseExpressionStatement(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:497)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:988)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBlockLike(PrettyPrinterSwitch.java:1121)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBlock(PrettyPrinterSwitch.java:1104)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBlock(PrettyPrinterSwitch.java:322)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBlock(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:394)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseFunctionExpression(PrettyPrinterSwitch.java:279)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseFunctionExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:334)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseArgument(PrettyPrinterSwitch.java:723)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseArgument(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:974)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:978)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseParameterizedCallExpression(PrettyPrinterSwitch.java:713)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseParameterizedCallExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:965)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseExpressionStatement(PrettyPrinterSwitch.java:392)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseExpressionStatement(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:497)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:988)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBlockLike(PrettyPrinterSwitch.java:1121)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.processBlock(PrettyPrinterSwitch.java:1104)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBlock(PrettyPrinterSwitch.java:322)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseBlock(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:394)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseFunctionExpression(PrettyPrinterSwitch.java:279)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseFunctionExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:334)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseParenExpression(PrettyPrinterSwitch.java:599)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseParenExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:686)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseParameterizedCallExpression(PrettyPrinterSwitch.java:711)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseParameterizedCallExpression(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:965)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseExpressionStatement(PrettyPrinterSwitch.java:392)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseExpressionStatement(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:497)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:1005)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.process(PrettyPrinterSwitch.java:988)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseScript(PrettyPrinterSwitch.java:183)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.caseScript(PrettyPrinterSwitch.java:1)
	at eu.numberfour.n4js.n4JS.util.N4JSSwitch.doSwitch(N4JSSwitch.java:87)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:166)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:58)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:159)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.doSwitch(PrettyPrinterSwitch.java:1)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinterSwitch.append(PrettyPrinterSwitch.java:138)
	at eu.numberfour.n4js.transpiler.print.PrettyPrinter.print(PrettyPrinter.java:56)
	at eu.numberfour.n4js.transpiler.PrettyPrintingStep.print(PrettyPrintingStep.java:37)
	at eu.numberfour.n4js.transpiler.AbstractTranspiler.prettyPrint(AbstractTranspiler.java:218)
	at eu.numberfour.n4js.transpiler.AbstractTranspiler.transpile(AbstractTranspiler.java:139)
	at eu.numberfour.n4js.transpiler.es.EcmaScriptTranspiler.transpile(EcmaScriptTranspiler.java:145)
	at eu.numberfour.n4js.transpiler.es.EcmaScriptSubGenerator.internalDoGenerate(EcmaScriptSubGenerator.java:145)
	at eu.numberfour.n4js.generator.common.AbstractSubGenerator.doGenerate(AbstractSubGenerator.java:127)
	... 39 more
```

**Comment by yoosiba** [comment]
So:
1.  code snippet contains broken code
2. Parser is not reporting issue
3. Validations are not reporting a problem
4. Trnaspiler expects valid code to work with so, as expected, it reports the issue when transpiling this snippet.

In the validations (unless we want to look deeper, in the parser that is) we should check for missing right hand side of the expression (see AST below)
![expr](https://cloud.githubusercontent.com/assets/944287/24852971/aec54f8e-1dd9-11e7-87e3-9d2d73d8e31e.png)

**Comment by kduske-n4** [comment]
I think we should at least consider whether or not this should be a parse error. I agree that it's probably better to catch this in validation to allow for better error messages, but since the validation is missing, it seems that this has slipped through somehow and there hasn't been a conscious decision to let it past the parser.

**Comment by yoosiba** [comment]
https://github.com/eclipse/n4js/issues/486
