### ISSUE TITLE
json-cycle missing in built in libraries

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#375]
N4JS runtime depends on `json-cycle` that is not provided with the ide. 
No projects can be executed (`Launched in Node.js`) or tested (`Test in Node.js`) until `json-cycle` is added to the dependencies and installed via Library Manager.

To reproduce:

1. ensure you have no `json-cycle` installed (check with library manage, uninstall if necessary)
2. Use context menu to run or test N4JS file, see errors
```
(SystemJS) Cannot find module 'json-cycle/cycle'
	Error: Cannot find module 'json-cycle/cycle'
	    at Function.Module._resolveFilename (module.js:470:15)
	    at Function.Module._load (module.js:418:25)
	    at Module.require (module.js:498:17)
	    at SystemJSNodeLoader.require [as _nodeRequire] (internal/module.js:20:19)
	    at C:\Users\me\N4JSIDE\plugins\eu.numberfour.n4js.external.libraries_0.0.1.201704061613\runtime\n4js-es5\src-gen\es\n4js-es5\rt\post-systemjs.js:158:53
	    at SystemJSNodeLoader.__sys.normalize (C:\Users\me\N4JSIDE\plugins\eu.numberfour.n4js.external.libraries_0.0.1.201704061613\runtime\n4js-es5\src-gen\es\n4js-es5\rt\post-systemjs.js:154:16)
	Error loading eu.numberfour.mangelhaft.assert/n4/mangel/assert/Assert as "eu.numberfour.mangelhaft.assert/n4/mangel/assert/Assert" from prj/mod
```

**Comment by JensN4** [comment]
In the new mangelhaft version, we do not need jscon-cycle anymore. So I close this bug as obsolete.
