### ISSUE TITLE
cannot run tests in project with N4JSC.jar

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#378]
Running all tests in the project with N4JSC.jar breaks at runtime. 
Running tests on the project inside N4JSIDE works fine.
[used latest public N4JSC.jar](http://n4js.s3-website.eu-central-1.amazonaws.com/ide/n4jsc.jar)
```
me$ java -jar n4jsc.jar -t allprojects -pl . -v --test ./mylib
 INFO: Generating mylib
 INFO:   Generating resource file:/Users/me/Desktop/n4js/mylib/src/GreeterModule_mylib.n4js
 INFO:   Generating resource file:/Users/me/Desktop/n4js/mylib/tst/TestGreeter.n4js
======= =======
Error: No main nor exec option given!
    at Object.n4.handleMainModule (/private/var/folders/ng/pb6yshfd607gdbpzspzy5thw0000gp/T/ide-nodejs-env/n4js-es5/rt/post-systemjs.js:34:35)
    at /private/var/folders/ng/pb6yshfd607gdbpzspzy5thw0000gp/T/ide-nodejs-env/n4js-node/run.js:30:24
    at Object.exports.runWith (/private/var/folders/ng/pb6yshfd607gdbpzspzy5thw0000gp/T/ide-nodejs-env/n4js-node/run.js:24:16)
    at /private/var/folders/ng/pb6yshfd607gdbpzspzy5thw0000gp/T/ide-nodejs-env/n4js-node/n4js-cli.js:19:29
    at Object.<anonymous> (/private/var/folders/ng/pb6yshfd607gdbpzspzy5thw0000gp/T/ide-nodejs-env/n4js-node/n4js-cli.js:31:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
eu.numberfour.n4js.hlc.N4jsc$ExitCodeException: The spawned tester 'eu.numberfour.n4js.tester.nodejs' exited with code=1 (wrong parameter set given)
	at eu.numberfour.n4js.hlc.N4jsc.startTester(N4jsc.java:1032)
	at eu.numberfour.n4js.hlc.N4jsc.compileAndExecute(N4jsc.java:953)
	at eu.numberfour.n4js.hlc.N4jsc.doMain(N4jsc.java:513)
	at eu.numberfour.n4js.hlc.N4jsc.main(N4jsc.java:345)
eu.numberfour.n4js.hlc.N4jsc$ExitCodeException: eu.numberfour.n4js.hlc.N4jsc$ExitCodeException: The spawned tester 'eu.numberfour.n4js.tester.nodejs' exited with code=1 (wrong parameter set given)
	at eu.numberfour.n4js.hlc.N4jsc.startTester(N4jsc.java:1037)
	at eu.numberfour.n4js.hlc.N4jsc.compileAndExecute(N4jsc.java:953)
	at eu.numberfour.n4js.hlc.N4jsc.doMain(N4jsc.java:513)
	at eu.numberfour.n4js.hlc.N4jsc.main(N4jsc.java:345)
Caused by: eu.numberfour.n4js.hlc.N4jsc$ExitCodeException: The spawned tester 'eu.numberfour.n4js.tester.nodejs' exited with code=1 (wrong parameter set given)
	at eu.numberfour.n4js.hlc.N4jsc.startTester(N4jsc.java:1032)
	... 3 more
eu.numberfour.n4js.hlc.N4jsc$ExitCodeException: The spawned tester 'eu.numberfour.n4js.tester.nodejs' exited with code=1 (wrong parameter set given) exitcode: 6 (unsuccessful execution of the runner)
```

**Comment by yoosiba** [comment]
Two problems found so far:
* test catalog is not discovered correctly when testing a project is detected (fixed in db101fee2f45495cbdbde7cc214b1b9652716663)
* wrong runtime is bootstrapped, which result of #167
