### ISSUE TITLE
Cannot run test created with wizard, several problems

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#394]
Steps to reproduce:
* download n4jside
* create new project as library
* create new test project
* run created tests (Run Asa / Test with Node.js)

```
ReferenceError: Reflect is not defined
    at Function.<anonymous> (file:///path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/lang/n4js.lang/src-gen/es/n4js.lang/n4js/lang/N4Injector.js:808:19)
    at Map.forEach (native)
    at Function.prepareBindingsMap___n4 (file:///path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/lang/n4js.lang/src-gen/es/n4js.lang/n4js/lang/N4Injector.js:807:28)
    at Function.of___n4 (file:///path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/lang/n4js.lang/src-gen/es/n4js.lang/n4js/lang/N4Injector.js:870:34)
    at Object.execute (file:///path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/mangelhaft/eu.numberfour.mangelhaft.runner.ide/src-gen/es/eu.numberfour.mangelhaft.runner.ide/n4/mangel/runner/ide/IDENodeTestRunner.js:241:23)
    at execute (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-es5/src-gen/es/n4js-es5/rt/post-systemjs.js:215:30)
    at ensureEvaluated (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:3363:26)
    at Object.execute (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:3513:13)
    at doDynamicExecute (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:766:25)
    at link (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:964:20)
```

Installed versions:
node:  5.9.0
n4jside: Build time: 2017-05-03 12:04:43

**Comment by JensN4** [comment]
Updated node to 6.10.3
Now, the test can be started, but all tests are skipped ("not implemented") which is wrong:

```
Error: Not implemented: lib.tests/Test_lib/tests
at new N4ApiNotImplementedError (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-es5/src-gen/es/n4js-es5/rt/N4BuiltInClasses.js:190:25)
at lib.tests/Test_lib/tests:1:69
at interceptDeclare (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-es5/src-gen/es/n4js-es5/rt/post-systemjs.js:205:20)
at linkDeclarativeModule (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:3167:37)
at link (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:3133:11)
at Object.execute (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:3510:13)
at doDynamicExecute (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:766:25)
at link (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:964:20)
at doLink (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:623:7)
at updateLinkSetOnLoad (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-node/node_modules/systemjs/dist/system.src.js:669:18)
```

**Comment by JensN4** [comment]
Noticed an oddity: the generated tests was called Test_lib.test.n4js.
Renamed to Test.n4js.

Now both tests fail:
```
(SystemJS) Cannot find module 'json-cycle/cycle'
Error: Cannot find module 'json-cycle/cycle'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at SystemJSNodeLoader.require [as _nodeRequire] (internal/module.js:20:19)
at /path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-es5/src-gen/es/n4js-es5/rt/post-systemjs.js:158:53
at SystemJSNodeLoader.__sys.normalize (/path/n4jside.app/Contents/Eclipse/plugins/eu.numberfour.n4js.external.libraries_0.0.1.201705031213/runtime/n4js-es5/src-gen/es/n4js-es5/rt/post-systemjs.js:154:16)
Error loading eu.numberfour.mangelhaft.assert/n4/mangel/assert/Assert as "eu.numberfour.mangelhaft.assert/n4/mangel/assert/Assert" from lib.tests/Test
```

**Comment by JensN4** [comment]
Manually installed package json-cycle via library manager
Now the tests are working.

All this should have work from the very beginning!

**Comment by JensN4** [comment]
General Acceptance Criteria:

- creating a project
- creating a test project with a test
- running that test

MUST WORK

**Comment by lbeurerkellner** [comment]
The greeter-test filename is inferred from the project name (Test_\<project name\>.n4js). Your project must have been called `lib.tests`.  That's where the considerably odd filename stems from.

While reproducing this on my machine I also noticed, that the mangelhaft import in the file hasn't been renamed as part of the org.eclipse renaming of mangelhaft. It still generates `import { Assert } from "n4/mangel/assert/Assert"` instead of `"org/eclipse/n4js/mangelhaft/assert/Assert"`.

The *Not implemented* problem is caused by the choice of project name `lib.tests`. When launching the test, the dot is converted/recognized as a module qualifier separator. So instead of looking for tests in the module `Test_lib.test`, the implementation of the tests is assumed to be in a module `test` in the folder `Test_lib`. That's why the implementation is not found. Obviously, renaming fixes that, although it should absolutely work right from the beginning. This becomes apparent from the line `at lib.tests/Test_lib/tests:1:69` in the stack trace.

I could not reproduce any of the node dependencies related issues. After renaming the file and updating the mangelhaft import, everything worked as expected.

I will look into the issues I could reproduce and also create a SWTBot test, so that we can avoid this type of regression in the future.

**Comment by lbeurerkellner** [comment]
Mirrored to https://github.com/eclipse/n4js/issues/108
