### ISSUE TITLE
Organise imports list is broken when importing type and function returning that type (both need to be used in code)

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#48]
IDEBUG-526
 consider file

```
export interface IB{}
export function f():IB{return null;}
export function fx(){}
```

and in other file we import those:

```
import { fx , f , IB } from "imports/ImportData"
var IB meta = f();
```

when doing organise imports, {{f}} is not removed from import list.
Additionally there is exception thrown (see below)

Note:
- broken

```
// "ImportData" file
export interface IB{}
export function f():any{return null;}
export function fx(){}

//importing file
import { fx , f , IB } from "imports/ImportData"
var IB x;
var meta = f();
```
- works

```
// "ImportData" file
export interface IB{}
export function f():IB{return null;}
export function fx(){}

//importing file
import { fx , f , IB } from "imports/ImportData"
var meta = f();
```

Thrown exception:

```
5343382 [main] WARN  eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImportsHandler  - Unrecognised RT-exception
java.lang.IllegalArgumentException: The 'no duplicates' constraint is violated
    at org.eclipse.emf.common.util.AbstractEList.set(AbstractEList.java:264)
    at org.eclipse.emf.common.util.AbstractEList$EListIterator.doSet(AbstractEList.java:959)
    at org.eclipse.emf.common.util.AbstractEList$EListIterator.set(AbstractEList.java:937)
    at java.util.List.sort(List.java:482)
    at java.util.Collections.sort(Collections.java:175)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImports.sortByName(N4JSOrganizeImports.java:458)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImports.extractPureText(N4JSOrganizeImports.java:615)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImports.lambda$1(N4JSOrganizeImports.java:181)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImports$$Lambda$598/766098972.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImports.getOrganizedImportSection(N4JSOrganizeImports.java:185)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImportsHandler$2.exec(N4JSOrganizeImportsHandler.java:315)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImportsHandler$2.exec(N4JSOrganizeImportsHandler.java:1)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:121)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImportsHandler.doOrganizeImports(N4JSOrganizeImportsHandler.java:299)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImportsHandler.organizeEditor(N4JSOrganizeImportsHandler.java:248)
    at eu.numberfour.ide.n4js.ui.organize.imports.N4JSOrganizeImportsHandler.execute(N4JSOrganizeImportsHandler.java:115)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1098)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1504)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1500)
    at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:496)
    at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:601)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5640)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
    at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2105)
    at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2329)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5702)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5139)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5288)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3666)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at eu.numberfour.ide.product.N4Application.start(N4Application.java:137)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by torstenkraemer** [comment]
fixed on branch IDE-2247
